WebMVC_eSport/Controllers/EQUIPOesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebMVC_eSport.Models;

namespace WebMVC_eSport.Controllers
{
    public class EQUIPOesController : Controller
    {
        private eSportsEntities db = new eSportsEntities();

        // GET: EQUIPOes
        public ActionResult Index()
        {
            return View(db.EQUIPO.ToList());
        }

        // GET: EQUIPOes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EQUIPO eQUIPO = db.EQUIPO.Find(id);
            if (eQUIPO == null)
            {
                return HttpNotFound();
            }
            return View(eQUIPO);
        }

        // GET: EQUIPOes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: EQUIPOes/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdEquipo,NomEquipo,PaisEquipo")] EQUIPO eQUIPO)
        {
            if (ModelState.IsValid)
            {
                eQUIPO.IdEquipo = 0;
                db.EQUIPO.Add(eQUIPO);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(eQUIPO);
        }

        // GET: EQUIPOes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EQUIPO eQUIPO = db.EQUIPO.Find(id);
            if (eQUIPO == null)
            {
                return HttpNotFound();
            }
            return View(eQUIPO);
        }

        // POST: EQUIPOes/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdEquipo,NomEquipo,PaisEquipo")] EQUIPO eQUIPO)
        {
            if (ModelState.IsValid)
            {
                db.Entry(eQUIPO).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(eQUIPO);
        }

        // GET: EQUIPOes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EQUIPO eQUIPO = db.EQUIPO.Find(id);
            if (eQUIPO == null)
            {
                return HttpNotFound();
            }
            return View(eQUIPO);
        }

        // POST: EQUIPOes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            EQUIPO eQUIPO = db.EQUIPO.Find(id);
            db.EQUIPO.Remove(eQUIPO);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebMVC_eSport/Controllers/HeroeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebMVC_eSport.ProxyHeroe;

namespace WebMVC_eSport.Controllers
{
    public class HeroeController : Controller
    {
        ServicioHeroeClient miservHeroes = new ServicioHeroeClient();
        // GET: Heroes
        public ActionResult Index()
        {
            ViewBag.ListarHeroes = miservHeroes.ListarHerores();
            return View();
        }

        public ActionResult Update(HeroeBE objHeroe)
        {
            if (objHeroe == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            if (miservHeroes.HeroeUpdate(objHeroe) == true){

                return View(objHeroe);
            }
            else
            {
                return HttpNotFound();
            }
            
        }

        public ActionResult Delete(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            if (miservHeroes.HeroeDelete(id) == true)
            {
                return View(id);
            }
            else
            {
                return HttpNotFound();
            }

        }
    }
}

WebMVC_eSport/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - eSports-CRUD</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("eSports-CRUD", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("CRUD-EQUIPO", "Index", "EQUIPOes")</li>
                    <li>@Html.ActionLink("Listar Heroes", "Index", "Heroe")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>